config/routes.rb
Rails.application.routes.draw do
  namespace :users_backoffice do
    get 'welcome/index'
  end
  devise_for :users
  get 'login/index'
  
  resources :battle
  resources :types
  resources :bagmons
  root to: 'bagmons#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bagmon.rb
class Bagmon < ApplicationRecord
    belongs_to :type
end

app/models/type.rb
class Type < ApplicationRecord
    has_many :bagmons
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bagmons_controller.rb
class BagmonsController < UsersBackofficeController
  before_action :set_bagmon, only: %i[ show edit update destroy ]
  before_action :set_type_options #, only: %i[ show create new edit update ]

  def set_type_options
    @type_options = Type.all.pluck(:name, :id)
  end


  # GET /bagmons or /bagmons/type_id=1
  def index
    @bagmons = Bagmon.all
    if (params[:type_id])
      @bagmons = @bagmons.where(type_id: params[:type_id])
    end
  end

  # GET /bagmons/1 or /bagmons/1.json
  def show
  end

  # GET /bagmons/new
  def new
    @bagmon = Bagmon.new
  end

  # GET /bagmons/1/edit
  def edit
  end

  # POST /bagmons or /bagmons.json
  def create
    @bagmon = Bagmon.new(bagmon_params)

    respond_to do |format|
      if @bagmon.save
        format.html { redirect_to bagmon_url(@bagmon), notice: "Bagmon was successfully created." }
        format.json { render :show, status: :created, location: @bagmon }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bagmon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bagmons/1 or /bagmons/1.json
  def update
    respond_to do |format|
      if @bagmon.update(bagmon_params)
        format.html { redirect_to bagmon_url(@bagmon), notice: "Bagmon was successfully updated." }
        format.json { render :show, status: :ok, location: @bagmon }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bagmon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bagmons/1 or /bagmons/1.json
  def destroy
    @bagmon.destroy

    respond_to do |format|
      format.html { redirect_to bagmons_url, notice: "Bagmon was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bagmon
      @bagmon = Bagmon.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bagmon_params
      params.require(:bagmon).permit(:number, :name, :image, :type_id)
    end
end

app/controllers/battle_controller.rb
class BattleController < UsersBackofficeController

  def index
    @bagmons = Bagmon.all

    if (params[:bagmon1] && params[:bagmon2]) 
      @bagmon1 = Bagmon.find(params[:bagmon1])
      @bagmon2 = Bagmon.find(params[:bagmon2])
      @rounds = []

      lifeBagmon1 = 100
      lifeBagmon2 = 100
      @lifes = [[lifeBagmon1, lifeBagmon2]]
      # Random bagmon attack first
      bagmonAttacking = rand(1..2) == 1 ? @bagmon1 : @bagmon2


      while (lifeBagmon1 > 0 && lifeBagmon2 > 0) do

        # Bagmon 1 attack bagmon 2 and remove random between 5 adn 10 life points

        if (bagmonAttacking == @bagmon1)
          attack = rand(5..15)
          lifeBagmon2 -= attack
          @rounds << @bagmon1.name + " attacked " + @bagmon2.name+ " and remove #{attack} life points"
          @lifes << [lifeBagmon1, lifeBagmon2]
          bagmonAttacking = @bagmon2
        else
          attack = rand(5..15)
          lifeBagmon1 -= attack
          @rounds << @bagmon2.name + " attacked " + @bagmon1.name + " and remove #{attack} life points"
          @lifes << [lifeBagmon1, lifeBagmon2]
          bagmonAttacking = @bagmon1
        end
      end

      # Display winner
      if (lifeBagmon1 <= 0)
        @rounds << @bagmon2.name + " won!"
        @vencedor = @bagmon2
      elsif (lifeBagmon2 <= 0)
        @rounds << @bagmon1.name + " won!"
        @vencedor = @bagmon1
      end
    end

  end

end

app/controllers/types_controller.rb
class TypesController < UsersBackofficeController
  before_action :set_type, only: %i[ show edit update destroy ]

  # GET /types or /types.json
  def index
    @types = Type.all
  end

  # GET /types/1 or /types/1.json
  def show
  end

  # GET /types/new
  def new
    @type = Type.new
  end

  # GET /types/1/edit
  def edit
  end

  # POST /types or /types.json
  def create
    @type = Type.new(type_params)

    respond_to do |format|
      if @type.save
        format.html { redirect_to type_url(@type), notice: "Type was successfully created." }
        format.json { render :show, status: :created, location: @type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /types/1 or /types/1.json
  def update
    respond_to do |format|
      if @type.update(type_params)
        format.html { redirect_to type_url(@type), notice: "Type was successfully updated." }
        format.json { render :show, status: :ok, location: @type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1 or /types/1.json
  def destroy
    @type.destroy

    respond_to do |format|
      format.html { redirect_to types_url, notice: "Type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type
      @type = Type.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def type_params
      params.require(:type).permit(:name, :color)
    end
end

app/controllers/users_backoffice/welcome_controller.rb
class UsersBackoffice::WelcomeController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/controllers/users_backoffice_controller.rb
class UsersBackofficeController < ApplicationController
    before_action :authenticate_user!
    layout 'users_backoffice'
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bagmons_helper.rb
module BagmonsHelper
end

app/helpers/battle_helper.rb
module BattleHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_backoffice/welcome_helper.rb
module UsersBackoffice::WelcomeHelper
end

app/helpers/users_backoffice_helper.rb
module UsersBackofficeHelper
end

app/views/bagmons/_form.html.erb
<%= form_with(model: bagmon, local: true) do |form| %>
  <% if bagmon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bagmon.errors.count, "error") %> prohibited this bagmon from being saved:</h2>

      <ul>
      <% bagmon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group mb-3">
    <%= form.label :number, class: "input-group-text" %>
    <%= form.number_field :number, class: "form-control"%>
  </div>

  <div class="input-group mb-3">
    <%= form.label :name, class: "input-group-text" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="input-group mb-3">
    <%= form.label :image, class: "input-group-text" %>
    <%= form.text_field :image, class: "form-control" %>
  </div>

  <div class="input-group mb-3">
    <%= form.label :type_id, class: "input-group-text" %>
    <%= form.select("type_id", @type_options, {include_blank: 'Selecione...', class: "form-select"}, {:multiple => false}) %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/bagmons/edit.html.erb
<div class="container">

<h1>Editing Bagmon</h1>

<%= render 'form', bagmon: @bagmon %>

<%= link_to 'Show', @bagmon, class:"btn btn-primary" %> |
<%= link_to 'Back', bagmons_path, class:"btn btn-primary" %>
</div>

app/views/bagmons/index.html.erb
<style>

    body {
        background: url(https://bagdex.com.br/wp-content/uploads/2022/09/fundo_site_01.png) no-repeat;
        background-size: cover;
        background-position: center;
        background-attachment: fixed;
        
    }
</style>

<div class="container">

<div style="margin-top: 10px">
  <form action="/bagmons">
      <div class="d-flex justify-content-start">
          <div class="form-group">
                <select required id="type_id" name="type_id" class="form-control">
                    <option selected disabled>All types</option>
                    <% @type_options.each do |type| %>
                        <option value="<%= type[1] %>"><%= type[0] %></option>
                    <% end %>
                </select>
            </div>
        <button type="submit" class="btn btn-success">Filter</button>
      </div>
  </form>
</div>
  <div class="d-flex align-items-center justify-content-between">
  <h1>Bagmons</h1>

  <%= link_to 'New Bagmon', new_bagmon_path, class:'btn btn-dark' %>
  </div>
  <div style='display: flex; flex-wrap: wrap; width: 100%; gap: 1rem; justify-content: space-between;'>
    <% @bagmons.each do |bagmon| %>
      <a style='text-decoration: none; background: <%=bagmon.type.color %>' href='/bagmons/<%= bagmon.id %>'>
        <div style=' color: white; display: flex; flex-direction: column; justify-content: center; align-items: center; height: 100%;'>
          <h3><%= bagmon.name%> #<%=bagmon.id %></h2>
          <div style='width: 100%; height: 100%; display: flex; justify-content: center; align-items: center;'>
            <%= image_tag bagmon.image, height: "400" %>
          </div>
        </div>
      </a>
    <% end %>
  </div>
</div>


app/views/bagmons/new.html.erb
<div class="container">

<h1>New Bagmon</h1>

<%= render 'form', bagmon: @bagmon %>

<%= link_to 'Back', bagmons_path, class:"btn btn-primary" %>
</div>

app/views/bagmons/show.html.erb
<body style='background-color: <%=@bagmon.type.color %>'>
  <div style='display: flex; flex-direction: column; align-items: center;'>
    <div class="card border-light mb-3" style="width: 18rem; top: 1rem;
      left: 0;
      right: 0;
      z-index: 3000;">
        <h1 style='text-align: center; background: <%=@bagmon.type.color %>; padding: 1.5rem;'><%= @bagmon.name %> #<%= @bagmon.number%></h1>
          <div style='background-color: white; display: flex; flex-direction: column; padding: 1.5rem;'>
    
            <p>
              <strong>Type:</strong>
              <%= @bagmon.type.name  %>
            </p>

            <p>
              <%= image_tag @bagmon.image, width: "250" %>
            </p>

            <div>
              <%= link_to 'Edit', edit_bagmon_path(@bagmon), class:"btn btn-warning" %>
              <%= link_to 'Back', bagmons_path, class:"btn btn-primary" %>
              <%= link_to 'Delete', bagmon_path(@bagmon), method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>

            </div>
          </div>
    </div>
  </div>
</body>

app/views/battle/index.html.erb
<style>

    body {
        background: url(https://bagdex.com.br/wp-content/uploads/2022/09/fundo_site_01.png) no-repeat;
        background-size: cover;
        background-position: center;
        background-attachment: fixed;
        
    }
</style>

<div class="container">
    <p id='data' style="display: none;">
    <%= @rounds %>
    </p>

    <p id='lifes' style="display: none;">
        <%= @lifes %>
    </p>

    <% if @bagmon1 && @bagmon2 %>
        <div class="container d-flex flex-column gap-3" >
            <h1 class="text-center">Battle</h1>
            <div class="d-flex align-items-center justify-content-between">
                <div id="divBagmon1">
                    <p>
                    <%= image_tag @bagmon1.image, width: "400" %>
                    </p>
                    <h2 id="bagmon1">
                        Life:
                    </h2>
                </div>
                <p id="new">

                X
                </p>
                <div id="divBagmon2">
                    <p>
                        <%= image_tag @bagmon2.image, width: "400" %>
                    </p>
                    <h2 id="bagmon2">
                        Life: 
                    </h2>
                </div>
            </div>
            <div id="result" style="overflow: auto; max-height: 100px;">
            </div>
            <div id="resultAll" style="display: none;">
            </div>

            <div class="d-flex justify-content-center">
                <button id="show-all" class="btn btn-primary">
                    Show all
                </button>
                <button id="hide-all" class="btn btn-primary" style="display: none;" >
                    Hide all
                </button>
            </div>
        </div>
    <% else %>
        <h1 class="text-center mb-3">Choose 2 Bagmons</h1>
        <form action="/battle" class="container d-flex flex-column gap-3 w-50">
            <div class="d-flex flex-row gap-3 align-items-center">
                <div class="form-group w-50">
                    <label for="bagmon1">Bagmon 1</label>
                    <select required id="bagmon1" name="bagmon1" class="form-control">
                        <option selected disabled>Select...</option>
                        <% @bagmons.each do |bagmon| %>
                            <option value="<%= bagmon.id %>"><%= bagmon.name %></option>
                        <% end %>
                    </select>
                </div>
                <p>
                X
                </p>
                <div class="form-group w-50">
                    <label for="bagmon2">Bagmon 2</label>
                    <select required id="bagmon2" name="bagmon2" class="form-control">
                        <option selected disabled>Select...</option>
                        <% @bagmons.each do |bagmon| %>
                            <option value="<%= bagmon.id %>"><%= bagmon.name %></option>
                        <% end %>
                    </select>
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Battle</button>
        </form>
    <% end %>

    <% if @bagmon1 && @bagmon2 %>
</div>

    <script>

        const rounds = JSON.parse(document.getElementById('data').innerHTML)
        const lifes = JSON.parse(document.getElementById('lifes').innerHTML)

        function delay(ms) {
            return new Promise(resolve => setTimeout(resolve, ms));
        }

        // To each round delay and console.log the round

        async function battle() {

            let bagmon1 = document.querySelector('#bagmon1')
            let bagmon2 = document.querySelector('#bagmon2')

            for (let i = 0; i < rounds.length; i++) {

                await delay(300);
                document.querySelector('#bagmon2').innerHTML = `<h2 class="text-center"> Life: ${lifes[i][1]}</h2>`
                document.querySelector('#bagmon1').innerHTML = `<h2 class="text-center"> Life: ${lifes[i][0]}</h2>`

                await delay(300);
                document.querySelector('#result').innerHTML = `<p class="text-center">${rounds[i]}</p>`
                document.querySelector('#resultAll').innerHTML += `<p class="text-center">${rounds[i]}</p>`
                document.querySelector('#bagmon2').innerHTML = `<h2 class="text-center"> Life: ${lifes[i][1]}</h2>`
                document.querySelector('#bagmon1').innerHTML = `<h2 class="text-center"> Life: ${lifes[i][0]}</h2>`
                window.scrollTo(0, document.body.scrollHeight);

            }
            if (lifes[rounds.length - 1][0] > lifes[rounds.length - 1][1]) {
                document.querySelector('#divBagmon1').style.backgroundColor = "green"
                document.querySelector('#divBagmon2').style.backgroundColor = "red"

            } else {
                document.querySelector('#divBagmon2').style.backgroundColor = "green"
                document.querySelector('#divBagmon1').style.backgroundColor = "red"
            }
            document.querySelector('#new').innerHTML = `<a class="btn btn-success" href="/battle" role="button">New Battle</a>`

        }

        

        document.querySelector('#show-all').addEventListener('click', () => {
            document.querySelector('#result').style.overflow = 'unset'
            document.querySelector('#result').style.maxHeight = 'unset'
            document.querySelector('#resultAll').style.display = 'block'
            document.querySelector('#result').style.display = 'none'
            document.querySelector('#show-all').style.display = 'none'
            document.querySelector('#hide-all').style.display = 'block'
            window.scrollTo(0, document.body.scrollHeight);

        })

        document.querySelector('#hide-all').addEventListener('click', () => {
            document.querySelector('#result').style.overflow = 'auto'
            document.querySelector('#result').style.maxHeight = '100px'
            document.querySelector('#resultAll').style.display = 'none'
            document.querySelector('#result').style.display = 'block'
            document.querySelector('#show-all').style.display = 'block'
            document.querySelector('#hide-all').style.display = 'none'
            window.scrollTo(0, document.body.scrollHeight);

        })

        battle();

    </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BagdexRuby</title>
    <%= favicon_link_tag asset_path('logo_bagdex.png') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    
    <%= yield %>
  </body>
</html>

app/views/layouts/users_backoffice.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BagdexRuby</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<nav class="navbar sticky-top navbar-expand-lg" style="background-color: #0A265D;
                    backdrop-filter: blur(10px);
                    background-color: rgba(10,38,93,0.5);
                    ">
  <div class="container-fluid">
      <div class="container">
        <a class="navbar-brand" href="/">
      <img src="/logo_bagdex.png" alt="Bagdex" width="100">
    </a>
  </div>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link text-white active" aria-current="page" href="/">Bagmons</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white active" href="/types">Types</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white active" href="/battle">Battle</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white active" href="/users/edit">My Account</a>
        </li>
        <li class="nav-item">
            <%= link_to "Logoff", destroy_user_session_path, class:'btn btn-dark' , method: :delete %>
        </li>
      </ul>
    </div>
  </div>
</nav>

  <body>
    
    <%= yield %>
  </body>
</html>

app/views/types/_form.html.erb
<%= form_with(model: type, local: true) do |form| %>
  <% if type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
      <% type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group mb-3">
    <%= form.label :name, class: "input-group-text"  %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="input-group mb-3">
    <%= form.label :color, class: "input-group-text"  %>
    <%= form.text_field :color, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-success" %>
  </div>
  
<% end %>

app/views/types/edit.html.erb
<div class="container">
    <h1>Editing Type</h1>

    <%= render 'form', type: @type %>

    <%= link_to 'Show', @type, class:"btn btn-primary" %> |
    <%= link_to 'Back', types_path, class:"btn btn-primary" %>
</div>

app/views/types/index.html.erb

<div class="container">

  <div class="d-flex align-items-center justify-content-between">
    <h1>Types</h1>
    <%= link_to 'New Type', new_type_path, class:'btn btn-dark' %>
  </div>
  
  <table class="table.table-responsive">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Color</th>
        <th scope="col" colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @types.each do |type| %>
        <tr style="background: <%=type.color %>">
          <td><%= type.name %></td>
          <td><%= type.color %></td>
          <td><%= link_to 'View', type, class: "btn btn-primary", style: "--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;" %></td>
          <td><%= link_to 'Edit', edit_type_path(type), class: "btn btn-warning btn-sm", style: "--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;" %></td>
          <td><%= link_to 'Destroy', type, class: "btn btn-danger btn-sm", style: "--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>


app/views/types/new.html.erb
<div class="container">

<h1>New Type</h1>

<%= render 'form', type: @type %>

<%= link_to 'Back', types_path %>
</div>

app/views/types/show.html.erb
<div class="container">

  <h1>Type: </h1>
  <p>
  <strong>Name:</strong>
  <%= @type.name %>
  </p>

  <p>
    <strong>Color:</strong>
    <%= @type.color %>
  </p>

  <%= link_to 'Edit', edit_type_path(@type), class:"btn btn-warning" %> |
<%= link_to 'Back', types_path, class:"btn btn-primary" %>
</div>




app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users_backoffice/welcome/index.html.erb
<h1>UsersBackoffice::Welcome#index</h1>
<p>Find me in app/views/users_backoffice/welcome/index.html.erb</p>